# Generated by Django 3.1.3 on 2020-11-26 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201126_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='adviser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(choices=[('Filipino', 'Filipino'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Araling Panlipunan', 'Araling Panlipunan'), ('Edukasyon sa Pagpapakatao', 'Edukasyon sa Pagpapakatao'), ('Edukasyong Pantahanan at Pangkabuhayan', 'Edukasyong Pantahanan at Pangkabuhayan'), ('MAPEH', 'MAPEH'), ('Mother Tongue', 'Mother Tongue')], max_length=255),
        ),
    ]
