# Generated by Django 3.1.3 on 2020-11-27 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='adviser_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
