# Generated by Django 3.1.3 on 2020-11-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201127_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_level',
            field=models.CharField(default='Grade 1', max_length=20),
        ),
    ]
