# Generated by Django 3.1.3 on 2020-11-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_subject_subject_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
