# Generated by Django 3.1.3 on 2020-11-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201128_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled',
            field=models.IntegerField(default=0),
        ),
    ]
