# Generated by Django 3.1.3 on 2020-11-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_student_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.subject'),
        ),
    ]
